// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZrx-T9XDxex7wD3lbGp8IiUINLtJcMRI',
    appId: '1:394024930348:web:726c1d19179a0b67f91589',
    messagingSenderId: '394024930348',
    projectId: 'awesome-toeic',
    authDomain: 'awesome-toeic.firebaseapp.com',
    databaseURL: 'https://awesome-toeic-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'awesome-toeic.appspot.com',
    measurementId: 'G-6XW25WZ7M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn2jeVeOKkN6b7GADEzZ9fAHtpFpFTXoU',
    appId: '1:394024930348:android:e7e2217f2ae669e6f91589',
    messagingSenderId: '394024930348',
    projectId: 'awesome-toeic',
    databaseURL: 'https://awesome-toeic-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'awesome-toeic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ipL4bPY3jtPVNTBwEKQ-JA8d97wfV64',
    appId: '1:394024930348:ios:4e2a42c64c5d3949f91589',
    messagingSenderId: '394024930348',
    projectId: 'awesome-toeic',
    databaseURL: 'https://awesome-toeic-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'awesome-toeic.appspot.com',
    iosClientId: '394024930348-njp59cjipfqf2prrhrar01jj4c5b68as.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterToeicQuiz2',
  );
}
